# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-toml


-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        name: black format
        stages:
          - "commit"

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
    -   id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place]

-   repo: local
    hooks:
    -   id: pytest-check
        name: run tests
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
